# perfana component values.

# If secretName is non-empty, env variable MONGO_URL, MONGO_OPLOG_URL and METEOR_SETTINGS set by secret.
# If value is non-empty, the secret is also created (otherwise the secret must be already deployed).
mongoUrl:
  secretName: mongo-url 
  value:
mongoOplogUrl: 
  secretName: mongo-url
  value:
meteorSettings:
  secretName: meteor-settings
  value:

# optional image pull secret
imagePullSecrets:
  - name: regcred

# securityContext at container-level
securityContext: {}

perfanaFe:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-fe
    tag: perfana-2.4.1
    pullPolicy: Always
  deploymentStrategy: RollingUpdate
  service:
    type: ClusterIP
    port: 3000
    targetPort: http
  ingress:
    enabled: false
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   cert-manager.io/cluster-issuer: "<issuer>"
    # hosts:
    #   - host: <hostname>
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific
    # tls:
    #   - hosts:
    #       - <hostname>
    #     secretName: perfana-<hostname>-tls
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 512Mi
  ## Environment variables
  env:
    ROOT_URL: http://localhost:4000
    PORT: 3000
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    enabled: false
    name: perfana-fe

perfanaGrafana:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-grafana
    tag: perfana-2.4.1
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Sync interval
  env:
    SYNC_INTERVAL: 30000  # 30 seconds
    MYSQL_HOST: mysql-headless
    MYSQL_USER: grafana
  envFromSecrets:
  - name: MYSQL_PASSWORD
    valueFrom:
      secretKeyRef:
        key: mysql-password
        name: mysql-credentials
  serviceAccount:
    enabled: false
    name: perfana-grafana
  
perfanaCheck:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-check
    tag: perfana-2.4.1
    pullPolicy: Always
  labels: {}
  annotations: {}
  service:
    type: ClusterIP
    port: 9191
    targetPort: http
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Environment variables
  env: 
    SPRING_PROFILES_ACTIVE: "prd"
    JAVA_TOOL_OPTIONS: -Dlogging.level.root=INFO
  serviceAccount:
    enabled: false
    name: perfana-check

perfanaSnapshot:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-snapshot
    tag: perfana-2.4.1
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    enabled: false
    name: perfana-snapshot
