# perfana component values.


mongoUrl:
  secretName:
  value:
mongoOplogUrl:
  secretName:
  value:
meteorSettings:
  secretName:
  value:

# If existingSecret exists, the chart will mount files from a secret. See readme.md for the required keys
# existingSecret: perfana-secrets

# optional image pull secret
# imagePullSecrets:
#   - name: regcred

securityContext: {}
containerSecurityContext: {}

perfanaFe:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-fe
    tag: perfana-2.4.3
    pullPolicy: Always
  deploymentStrategy: RollingUpdate
  service:
    type: ClusterIP
    port: 3000
    targetPort: http
  ingress:
    enabled: false
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   cert-manager.io/cluster-issuer: "<issuer>"
    # hosts:
    #   - host: <hostname>
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific
    # tls:
    #   - hosts:
    #       - <hostname>
    #     secretName: perfana-<hostname>-tls
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 512Mi
  ## Environment variables
  env:
    ROOT_URL: http://localhost:4000
    PORT: 3000
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    enabled: false
    name: perfana-fe
  configuration:
    # https://docs.perfana.io/docs/settings/settings.html#organisations
    # organisations:
    # - name: Perfana
    #   description: Perfana
    
    # https://docs.perfana.io/docs/settings/settings.html#perfana-url
    perfanaUrl: "https://perfana.myhost.com"

    # https://docs.perfana.io/docs/settings/settings.html#perfana-check-url  
    perfanaCheckUrl: "http://perfana-check:9191"   
    
    # https://docs.perfana.io/docs/settings/settings.html#auto-compare-testruns
    autoCompareTestRuns: true
    
    # https://docs.perfana.io/docs/settings/settings.html#auto-set-baseline-testrun
    autoSetBaselineTestRun: false
 
    # https://docs.perfana.io/docs/settings/settings.html#helmet-framesrc
    helmet:
      frameSrc:
      - "https://*.myhost.com"

    # https://docs.perfana.io/docs/settings/settings.html#login-expiration-in-days
    loginExpirationInDays: 1

    # https://docs.perfana.io/docs/settings/settings.html#retention-settings
    prometheusRetention: 2592000
    influxDbRetention: 2592000
    elasticSearchRetention: 2592000
    snapshotExpires: 7776000


    public:
    # https://docs.perfana.io/docs/settings/settings.html#forbid-client-account-creation
      forbidClientAccountCreation: false  
    
    # https://docs.perfana.io/docs/settings/settings.html#perfana-url-1
      perfanaUrl: "https://perfana.myhost.com"   
    
    # https://docs.perfana.io/docs/settings/settings.html#jaeger-url  
      # jaegerUrl: "https://jaeger.myhost.com"
    
    # https://docs.perfana.io/docs/settings/settings.html#jaeger-limit
      # jaegerLimit: 500
    
    # https://docs.perfana.io/docs/settings/settings.html#pyroscope-url  
      # pyroscopeUrl: "https://pyroscope.myhost.com"
    
    # https://docs.perfana.io/docs/settings/settings.html#override-login-button-text  
      # overrideLoginButtonText: "My company Login"
    
    # https://docs.perfana.io/docs/settings/settings.html#google-sign-in  
      # googleSignIn: true

    # https://docs.perfana.io/docs/settings/settings.html#custom-alert-tags
    # customAlertTags:
    # - key: application
    #   value: perfana-applications
    # - key: namespace
    #   value: perfana-test-environment     

    # https://docs.perfana.io/docs/settings/settings.html#omit-alert-tags
    # omitAlertTags:
    # - alertSource: alertmanager
    #   tag: kubernetes_pod_name
    # - alertSource: alertmanager
    #   tag: node  

perfanaGrafana:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-grafana
    tag: perfana-2.4.3
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Sync interval
  env:
    SYNC_INTERVAL: 30000  # 30 seconds
  #   MYSQL_HOST: mysql-headless
  #   MYSQL_USER: grafana
  # envFromSecrets:
  # - name: MYSQL_PASSWORD
  #   valueFrom:
  #     secretKeyRef:
  #       key: mysql-password
  #       name: mysql-credentials
  serviceAccount:
    enabled: false
    name: perfana-grafana
  
perfanaCheck:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-check
    tag: perfana-2.4.3
    pullPolicy: Always
  labels: {}
  annotations: {}
  service:
    type: ClusterIP
    port: 9191
    targetPort: http
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Environment variables
  env: 
    SPRING_PROFILES_ACTIVE: "prd"
    JAVA_TOOL_OPTIONS: -Dlogging.level.root=INFO
  serviceAccount:
    enabled: false
    name: perfana-check

perfanaSnapshot:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-snapshot
    tag: perfana-2.4.3
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAccount:
    enabled: false
    name: perfana-snapshot
