# perfana-fe values.

perfanaFe:

  replicaCount: 1

  image:
    repository: perfana/perfana-fe
    tag: 2.30.3
    pullPolicy: Always

  deploymentStrategy: RollingUpdate

  service:
    type: ClusterIP
    port: 3000
    targetPort: http

  ingress:
    enabled: false
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   nginx.ingress.kubernetes.io/affinity: cookie
    #   nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    #   nginx.ingress.kubernetes.io/session-cookie-name: route
    
    # path: /
    # hosts:
    #   - host: perfana.yourhost.com

    # tls:
    # - secretName: perfana.yourhost.com-tls
    #   hosts:
    #     - perfana.yourhost.com

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 512Mi

  ## Environment variables 
  env:
    ROOT_URL: http://localhost:4000
    PORT: 3000

  nodeSelector: {}

  tolerations: []

  affinity: {}


perfanaGrafana:

  replicaCount: 1

  image:
    repository: perfana/perfana-grafana
    tag: 2.7.0
    pullPolicy: Always

  resources: {} 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  ## Sync interval 
  env:
    SYNC_INTERVAL: 30000  # 30 seconds
  
perfanaCheck:

  replicaCount: 1

  image:
    repository: perfana/perfana-check
    tag: 2.4.0
    pullPolicy: Always
    
  service:
    type: ClusterIP
    port: 9191
    targetPort: http

  resources: {} 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  ## Environment variables
  env: 
    SPRING_PROFILES_ACTIVE: "prd"
    JAVA_TOOL_OPTIONS: -Dlogging.level.root=INFO


perfanaSnapshot:

  replicaCount: 1

  image:
    repository: perfana/perfana-snapshot
    tag: 2.7.1
    pullPolicy: Always
    
  resources: {} 
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 1Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

