# perfana component values.

# use existing secrets, e.g. when using sealed secrets
#existingSecret:
#  mongoUrl: mongo-url
#  mongoOplogUrl: mongo-oplog-url
#  meteorSettings: meteor-settings

# optional image pull secret
imagePullSecrets:
  - name: regcred

perfanaFe:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-fe
    tag: perfana-2.3.0
    pullPolicy: Always
  deploymentStrategy: RollingUpdate
  service:
    type: ClusterIP
    port: 3000
    targetPort: http
  ingress:
    enabled: false
    # annotations:
    #   kubernetes.io/ingress.class: nginx
    #   cert-manager.io/cluster-issuer: "<issuer>"
    # hosts:
    #   - host: <hostname>
    #     paths:
    #       - path: /
    #         pathType: ImplementationSpecific
    # tls:
    #   - hosts:
    #       - <hostname>
    #     secretName: perfana-<hostname>-tls
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 512Mi
  ## Environment variables
  env:
    ROOT_URL: http://localhost:4000
    PORT: 3000
  nodeSelector: {}
  tolerations: []
  affinity: {}

perfanaGrafana:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-grafana
    tag: perfana-2.3.0
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Sync interval
  env:
    SYNC_INTERVAL: 30000  # 30 seconds
  
perfanaCheck:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-check
    tag: perfana-2.3.0
    pullPolicy: Always
  labels: {}
  annotations: {}
  service:
    type: ClusterIP
    port: 9191
    targetPort: http
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 1
    #  memory: 1Gi
    # requests:
    #  cpu: 500m
    #  memory: 512Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  ## Environment variables
  env: 
    SPRING_PROFILES_ACTIVE: "prd"
    JAVA_TOOL_OPTIONS: -Dlogging.level.root=INFO

perfanaSnapshot:
  enabled: true
  replicaCount: 1
  image:
    repository: perfana/perfana-snapshot
    tag: perfana-2.3.0
    pullPolicy: Always
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 2
    #  memory: 2Gi
    # requests:
    #  cpu: 1
    #  memory: 1Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
