{{- if .Values.perfanaGrafana.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-grafana
  labels:
    app: perfana-grafana
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaGrafana.replicaCount }}
  selector:
    matchLabels:
      app: perfana-grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: perfana-grafana
        release: {{ .Release.Name }}
        {{- with .Values.perfanaGrafana.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.perfanaGrafana.annotations }}
      annotations: {{ toYaml .Values.perfanaGrafana.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.perfanaGrafana.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaGrafana.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-grafana
          image: "{{ .Values.perfanaGrafana.image.repository }}:{{ .Values.perfanaGrafana.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaGrafana.image.pullPolicy }}
          {{- with .Values.perfanaGrafana.command }}
          command:
          {{ toYaml . | nindent 10 }}
          {{- end}}
          {{- with .Values.securityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env: # ENV variables for your project
          {{- if .Values.mongoUrl.secretName }}
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                key: MONGO_URL
                name: {{ .Values.mongoUrl.secretName }}
          {{- end }}
          {{- range $key, $value := .Values.perfanaGrafana.env }}
          - name: {{ $key }}
            value: '{{ $value }}'
          {{- end }}
          {{- range .Values.perfanaGrafana.envFromSecrets }}
          {{print "- " (. | toYaml | nindent 12 | trim) }}
          {{- end }}


          resources:
{{ toYaml .Values.perfanaGrafana.resources | indent 12 }}
    {{- with .Values.perfanaGrafana.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaGrafana.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaGrafana.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end}}
