{{- if .Values.perfanaFe.ingress.enabled -}}
{{- $ingressPath := .Values.perfanaFe.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: perfana-fe
  labels:
    app: perfana-fe
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.perfanaFe.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
{{- if .Values.perfanaFe.ingress.tls }}
  tls:
  {{- range .Values.perfanaFe.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.perfanaFe.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: perfana-fe
              servicePort: http
  {{- end }}
{{- end }}
