apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-check
  labels:
    app: perfana-check
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaCheck.replicaCount }}
  selector:
    matchLabels:
      app: perfana-check
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: perfana-check
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: perfana-check
          image: "{{ .Values.perfanaCheck.image.repository }}:{{ .Values.perfanaCheck.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaCheck.image.pullPolicy }}
          ports:
            - name: {{ .Values.perfanaCheck.service.targetPort }}
              containerPort: {{ .Values.perfanaCheck.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env: # ENV variables for your project
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                key: MONGO_URL
                name: {{ .Values.existingSecret.mongoUrl | default "mongo-url" }}
      {{- range $key, $value := .Values.perfanaCheck.env }}
          - name: {{ $key }}
            value: '{{ $value }}'
      {{- end }}    
          resources:
{{ toYaml .Values.perfanaCheck.resources | indent 12 }}
    {{- with .Values.perfanaCheck.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaCheck.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaCheck.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
