{{- if .Values.perfanaSnapshot.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-snapshot
  labels:
    app: perfana-snapshot
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaSnapshot.replicaCount }}
  selector:
    matchLabels:
      app: perfana-snapshot
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: perfana-snapshot
        release: {{ .Release.Name }}
        {{- with .Values.perfanaSnapshot.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.perfanaSnapshot.annotations }}
      annotations: {{ toYaml .Values.perfanaSnapshot.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.perfanaSnapshot.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaSnapshot.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-snapshot
          image: "{{ .Values.perfanaSnapshot.image.repository }}:{{ .Values.perfanaSnapshot.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaSnapshot.image.pullPolicy }}
          {{- with .Values.perfanaSnapshot.command }}
          command:
          {{ toYaml . | nindent 10 }}
          {{- end}}
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env:
          {{- if .Values.mongoUrl.secretName }}
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                key: MONGO_URL
                name: {{ .Values.mongoUrl.secretName }}
                  {{- end }}
          {{- range $key, $value := .Values.perfanaSnapshot.env }}
          - name: {{ $key }}
            value: '{{ $value }}'
            {{- end }}
          {{- range .Values.perfanaSnapshot.envFromSecrets }}
          {{print "- " (. | toYaml | nindent 12 | trim) }}
          {{- end }}
          {{- range $key, $value := .Values.perfanaSnapshot.env }}
          - name: {{ $key }}
            value: '{{ $value }}'
          {{- end }}
          resources:
{{ toYaml .Values.perfanaSnapshot.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.perfanaSnapshot.volumeMounts }}
             {{- toYaml .Values.perfanaSnapshot.volumeMounts | nindent 10 }}
          {{- end }}
          {{- if .Values.existingSecret }}
          - name: perfana-snapshot-secrets
            mountPath: /secrets/perfana-mongo-urls-secret.env
            subPath: perfana-mongo-urls-secret.env 
          {{- end }}
      volumes:
      {{- if .Values.perfanaSnapshot.volumes }}
         {{- toYaml .Values.perfanaSnapshot.volumes | nindent 6 }}
      {{- end }}
      {{- if .Values.existingSecret }}
      - name: perfana-snapshot-secrets
        projected:
          sources:
          - secret:
              name: {{ .Values.existingSecret }}       
      {{- end }}

    {{- with .Values.perfanaSnapshot.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaSnapshot.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaSnapshot.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
