{{- if .Values.perfanaGrafana.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-grafana
  labels:
    app: perfana-grafana
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaGrafana.replicaCount }}
  selector:
    matchLabels:
      app: perfana-grafana
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: perfana-grafana
        release: {{ .Release.Name }}
    spec:
      {{- if .Values.perfanaGrafana.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaGrafana.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-grafana
          image: "{{ .Values.perfanaGrafana.image.repository }}:{{ .Values.perfanaGrafana.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaGrafana.image.pullPolicy }}
       
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          env: # ENV variables for your project
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                key: MONGO_URL
                {{- if not .Values.existingSecret.mongoUrl }}
                name: mongo-url
                {{- else }}
                name: {{ .Values.existingSecret.mongoUrl }}
                {{- end }}
      {{- range $key, $value := .Values.perfanaGrafana.env }}
          - name: {{ $key }}
            value: '{{ $value }}'
      {{- end }}    
          resources:
{{ toYaml .Values.perfanaGrafana.resources | indent 12 }}
    {{- with .Values.perfanaGrafana.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaGrafana.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaGrafana.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end}}
