{{- if not .Values.existingSecret }}
apiVersion: v1
stringData:
  MONGO_OPLOG_URL: {{ .Values.mongo.oplogUrl}}
kind: Secret
metadata:
  name: {{ .Values.mongoOplogUrl | default "mongo-oplog-url" }}
  namespace: perfana
type: Opaque
{{- end }}



