{{- if .Values.mongoOplogUrl.value }}
apiVersion: v1
stringData:
  MONGO_OPLOG_URL: {{ .Values.mongoOplogUrl.value }}
kind: Secret
metadata:
  name: {{ .Values.mongoOplogUrl.secretName }}
  namespace: perfana
type: Opaque
{{- end }}



