{{- if .Values.meteorSettings.value }}
apiVersion: v1
stringData:
  METEOR_SETTINGS: {{ .Values.meteorSettings.value | toJson | quote  }}
kind: Secret
metadata:
  name: {{ .Values.meteorSettings.secretName }}
  namespace: perfana
type: Opaque
{{- end }}
