{{- if not .Values.existingSecret }}
apiVersion: v1
stringData:
  MONGO_URL: {{ .Values.mongo.url}}
kind: Secret
metadata:
  name: {{ .Values.mongoUrl | default "mongo-url" }}
  namespace: perfana
type: Opaque
{{- end }}

