{{- if .Values.mongoUrl.value }}
apiVersion: v1
stringData:
  MONGO_URL: {{ .Values.mongoUrl.value }}
kind: Secret
metadata:
  name: {{ .Values.mongoUrl.secretName }}
  namespace: perfana
type: Opaque
{{- end }}
