{{- if not .Values.existingSecret }}
apiVersion: v1
stringData:
  METEOR_SETTINGS: {{ .Values.meteorSettings | toJson | quote  }}
kind: Secret
metadata:
  name: meteor-settings
  namespace: perfana
type: Opaque
{{- end }}

