# https://docs.perfana.io/docs/administration/administration.html#grafana-configuration
grafanaInstances:
- label: "Demo"
  clientUrl: "https://grafana.demo.perfana.cloud"
  serverUrl: "http://grafana"
  orgId: "1"
  username: admin@perfana.io
  password: perfana
  snapshotInstance: true
  trendsInstance: true
